//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candles
    {
        public int Id_Candle { get; set; }
        public string Plase_of_origin { get; set; }
        public string Product_name { get; set; }
        public string Material { get; set; }
        public string Color { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Diameter { get; set; }
        public string Fragrance { get; set; }
        public string Image { get; set; }
        public string Burning_time { get; set; }
        public Nullable<float> Old_Price { get; set; }
        public Nullable<float> New_Price { get; set; }
        public int Quantity { get; set; }
    }
}
