//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int Id_Cost { get; set; }
        public Nullable<int> Id_Candle { get; set; }
        public Nullable<int> Id_Users { get; set; }
        public string Status_Cost { get; set; }
        public string Column { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
        public string Telephon { get; set; }
        public string Email { get; set; }
        public string Date { get; set; }
        public string Address { get; set; }
    }
}
