//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id_Message { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
        public string Email { get; set; }
        public string Telephon { get; set; }
        public string Message1 { get; set; }
    }
}
