//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_Users { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Telephon { get; set; }
        public string Avatar { get; set; }
        public string Username { get; set; }
        public int Status { get; set; }
    }
}
